export const PROPOSAL_KIND_LABEL: Record<string, string> = {
  'inquiry-triage': 'Inquiry triage',
  'scripted-answer': 'Reply draft',
  'issue-summary': 'Handoff summary',
  'resident-context': 'Resident context',
  'variance-explanation': 'Variance explanation',
  'exception-summary': 'Exception summary',
  'close-checklist': 'Close checklist',
  'council-memo': 'Council briefing',
  'utility-exception': 'Usage exception',
  'utility-collections': 'Collections / shutoff',
  'utility-final-bill': 'Final bill',
  'payroll-exception': 'Payroll exception',
  'payroll-checklist': 'Payroll checklist',
  report: 'Report',
  'agenda-packet': 'Agenda / packet',
  'public-notice': 'Public notice',
  'records-triage': 'Records request',
  'delinquency-notice': 'Delinquency notice',
  'tax-certificate': 'Tax certificate',
  'ownership-change': 'Ownership change',
  'case-triage': 'Case triage',
  'inspection-prep': 'Inspection prep',
  'notice-draft': 'Violation notice',
  'case-aging': 'Case aging',
};
